# Generated by Django 4.1.6 on 2023-04-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='subscribe_arn',
            field=models.TextField(default='2', unique=True),
            preserve_default=False,
        ),
    ]
