# Generated by Django 4.1.6 on 2023-04-11 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_subscribe_arn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='subscribe_arn',
        ),
    ]
